# https://github.com/Koopex/FontInAss_mpv-script
# 脚本功能: 请求 FontInAss 子集化处理本地 ass 字幕


#---------------------------- 可用的快捷键 -----------------------------
#	script-binding font_in_ass/fonts  		#! 字体缺失（OSD）
#	script-binding font_in_ass/openLog  	#! 字体缺失（网页）
#-----------------------------------------------------------------------


#----------------- api 必须配置, 其他可选 -----------------
# 设置你的FontInAss服务地址, 默认端口为 8011 
# 示例 http://192.168.1.100:8011
server=
#--------------------- 以下可保持默认 ---------------------



#---------------------- 提示缺失信息 ----------------------
# 是否提示缺失信息
# 0: 不提示
# 1: 仅"字体"缺失时提示
# 2: "字体"或"字形"缺失时提示
# 不管选哪个, 控制台都能查看全部信息
reminder=1

# 提示方式
# yes:  总是使用屏幕消息提示 (即使有 uosc)
# no:   有 uosc 则使用 uosc 菜单, 没有则通过屏幕消息提示
always_osd=no


#---------- 通过屏幕消息提示字体缺失时的按键设置 ----------
# 复制字体名称
key_copy=Ctrl+c

# 查看日志
key_logs=f

# 忽略提示, 继续播放
key_close=SPACE

